### ISSUE TITLE
Last words wrong language (ttt_radio)

### ISSUE THREAD

**Issue by copyyy** [Tommy228/TTTDamagelogs#133]
(LAST WORDS) Shinra Blade: Een ongeindentificeerd lijk is a Traitor! *SPLUT*

Shinra's client language: Dutch
My language: English.
Eveything else is in English, just last words not. Forgot to translate that in code?^^

**Comment by Tommy228** [comment]
From what I see the translation is clientside.. wat

**Comment by Joschasa** [comment]
The strings itself come from the server (..\garrysmod\gamemodes\terrortown\gamemode\lang\english.lua), but the localization itself takes places clientside.
Do you have custom strings in english.lua or an own dutch.lua or s.th.? Gmod doesn't provide it: https://github.com/garrynewman/garrysmod/tree/master/garrysmod/gamemodes/terrortown/gamemode/lang

You can change the english.lua on your server yourself or copy it and create your own language file.

**Comment by copyyy** [comment]
We do have a custom dutch.lua file on the server but that shouldn't cause that, I guess?! I mean, it did work before, just not with the new update now.

**Comment by Joschasa** [comment]
Translation of ttt_radio is done on each client. Last words come from the client, who died.

For ttt_radio, only the needed information is distributed and every client translates it to his local language.
Last words are the last message of the dead person and get distributed as complete text.

The client using ttt_radio tries to translate this to english first, so that this message can be used as last words:
https://github.com/garrynewman/garrysmod/blob/master/garrysmod/gamemodes/terrortown/gamemode/cl_voice.lua#L313

The implementation has a bug:
The type message (quick_traitor) is translated using:
> local eng = LANG.GetTranslationFromLanguage(msg.text, "english")
and this is intendet behaviour and works well: "{player} is a traitor!" is retrieved.
But the target gets translated using RADIO.ToPrintable(target), which does not take a language as parameter. So the string "quick_corpse" gets translated using GetTranslation(target), which results in the locale version of the client (in your case his client uses the dutch.lua, so "quick_corpse" gets translated to "Een ongeindentificeerd lijk")

-> Not a bug in TTTDamagelogs, but in garrysmod / terrortown :)
