### ISSUE TITLE
Players with ' " ' in their name are immune to aslay

### ISSUE THREAD

**Issue by doctorluk** [Tommy228/TTTDamagelogs#203]
I guess that's an issue with how aslay expects its paramaters. If a player is named
Foo "LoL" Bar
aslay will throw a "no player found or player has immunity" error when trying to slay this person from the RDM Manager.

**Comment by Linkfan123** [comment]
I have an idea.
Put quotes around the whole name. That way, the command knows that is a string, so quotes in the string itself are fine.
But...
Now that I think about it...
@Tommy228 !!! I need some help in figuring out how to program this!!! Please!!!

**Comment by doctorluk** [comment]
Maybe just get the player's player-id or steam-id and use that instead?

**Comment by Linkfan123** [comment]
Yeah. That would be a work-around.
Oh, and the reason I wanted Tommy was because if I typed in "Foo "LoL" Bar", the command might think I'm trying to put in "Foo " and " Bar" as separate parameters. And that's no good.
Ahggg, ULX/Lua is so confusing! I wish I could make addons with C#.
*gasp* I think I have an idea...

**Comment by Tommy228** [comment]
Should be fixed.
