### ISSUE TITLE
No logs are being saved on crash

### ISSUE THREAD

**Issue by Quinlan102** [Tommy228/TTTDamagelogs#312]
I'm experiencing a crash that happens randomly when the map is rebuilding the console just freeze
and im wonding how and when does the rdm manager save the current round logs.
Cause one thing  I've noticed is when the server crashes at the end when the map is getting rebuilded I don't have any logs for that round.
I am not saying that the rdm manager is causing this.
I would just remove it for a few days but i need it in my server.
I have alot of custom weapons.

**Comment by MinIsMin** [comment]
When a round ends, the hook `TTTEndRound` in [oldlogs.lua](https://github.com/Tommy228/TTTDamagelogs/blob/master/lua/damagelogs/server/oldlogs.lua#L143-L167) is called.
The round data is being saved in the SQL(ite) DB.

What version of TTT Damagelogs are you using and since when does this crash occur?
Please test if without TTT Damagelogs it's crashing, too or not.
